add PHP/JAVASCRIPT OR RUBY minigame
WildCodeSchool/2023-02-Orleans-Spe-P2-C pull request #11
Opened 2023-03-17 13:34 UTC by NefytZ

2023-03-17 13:49 UTC, Chloebert approved these changes

2023-03-17 14:00 UTC, Chloebert submitted a review, later dismissed

2023-03-17 14:30 UTC, YDrogen requested changes

2023-03-17 14:30 UTC, YDrogen commented on src/scenes/scene-one.js
> +            let heart = this.add.image(90 + i * 49, 60, 'heart').setScale(0.16).setDepth(2);
const !!!!!!!!!!!

2023-03-17 14:30 UTC, YDrogen commented on .gitignore
> +package-lock.json
le `package-lock.json` ne va pas dans le `.gitignore`

2023-03-17 19:29 UTC, greegouze approved these changes

2023-03-18 10:16 UTC, YDrogen approved these changes

2023-03-18 10:16 UTC, merged