music
WildCodeSchool/2023-02-Orleans-Spe-P2-C pull request #13
Opened 2023-03-17 16:48 UTC by Chloebert

2023-03-17 19:01 UTC, greegouze approved these changes

2023-03-17 19:28 UTC, NefytZ submitted a review, later dismissed

2023-03-18 10:19 UTC, YDrogen requested changes

2023-03-18 10:19 UTC, YDrogen commented on src/scenes/scene-one.js
> +
Pas besoin de déclarer `music` ici

2023-03-18 10:19 UTC, YDrogen commented on src/scenes/scene-one.js
> +        music = this.sound.add('music1', { loop: true });
Ici, ça suffit, vu que `music` n'est utilisé que dans ce scope

2023-03-18 10:19 UTC, YDrogen commented on src/scenes/scene-three.js
> +let music;
idem

2023-03-18 10:19 UTC, YDrogen commented on src/scenes/scene-two.js
> +let music;
idem

2023-03-18 10:19 UTC, YDrogen commented on src/scenes/scene-two.js
> +        music = this.sound.add('music2', { loop: true });
idem

2023-03-19 21:05 UTC, YDrogen requested changes

2023-03-19 21:05 UTC, YDrogen commented on src/scenes/scene-one.js
> +
Ligne vide

2023-03-19 21:09 UTC, Chloebert commented on src/scenes/scene-one.js
> +
=(

2023-03-19 22:19 UTC, NefytZ approved these changes

2023-03-20 08:07 UTC, merged