uniformisation scene final + effet game over
WildCodeSchool/2023-02-Orleans-Spe-P2-C pull request #15
Opened 2023-03-18 15:39 UTC by greegouze

2023-03-18 21:17 UTC, YDrogen requested changes

2023-03-18 21:17 UTC, YDrogen commented on assets/images/creazy-boy.jpg
Ça s'écrit `crazy`
............

2023-03-20 07:51 UTC, Chloebert approved these changes

2023-03-20 08:08 UTC, YDrogen approved these changes

2023-03-20 08:20 UTC, YDrogen approved these changes

2023-03-20 08:20 UTC, merged