système de vie
WildCodeSchool/2023-02-Orleans-Spe-P2-C pull request #8
Opened 2023-03-16 09:47 UTC by greegouze

2023-03-16 11:51 UTC, Chloebert requested changes

2023-03-16 11:51 UTC, Chloebert commented on src/scenes/heartSystem.js
Je pense que ce serait mieux de le mettre dans un autre dossier genre services ?

2023-03-16 12:12 UTC, Chloebert approved these changes

2023-03-16 13:17 UTC, YDrogen commented on src/scenes/scene-two.js
> +import heartSystem from '../services/heartSystem.js';
Idem, beaucoup de let

2023-03-16 13:18 UTC, YDrogen commented on src/services/heartSystem.js
> +        this.lives --;
```suggestion
        this.lives--;
```

2023-03-16 13:53 UTC, Chloebert approved these changes

2023-03-16 15:29 UTC, Chloebert commented
> Nom du fichier plutôt `hearth-system` (J'avais pas vu, déso)

Plutôt 'health-system' je suppose 👀

2023-03-16 19:37 UTC, Chloebert approved these changes

2023-03-17 08:01 UTC, YDrogen approved these changes

2023-03-17 08:02 UTC, merged